# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170705_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=100)),
                ('banner_img', models.FileField(upload_to=b'')),
            ],
        ),
    ]
