# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_sliders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=100)),
                ('work_img', models.FileField(upload_to=b'')),
            ],
        ),
    ]
