# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170710_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='myfield',
        ),
        migrations.AddField(
            model_name='works',
            name='work_cat',
            field=models.CharField(choices=[(b'Comercial', b'Comercial'), (b'Residential', b'Residential'), (b'Galleria', b'Galleria')], default=1, max_length=256),
            preserve_default=False,
        ),
    ]
